const cerPrimeCifre =  {
    "01": "RIFIUTI DERIVANTI DA PROSPEZIONE, ESTRAZIONE DA MINIERA O CAVA, NONCHÉ DAL TRATTAMENTO FISICO O CHIMICO DI MINERALI",
    "02": "RIFIUTI PRODOTTI DA AGRICOLTURA, ORTICOLTURA, ACQUACOLTURA, SELVICOLTURA, CACCIA E PESCA, TRATTAMENTO E PREPARAZIONE DI ALIMENTI",
    "03": "RIFIUTI DELLA LAVORAZIONE DEL LEGNO E DELLA PRODUZIONE DI PANNELLI, MOBILI, POLPA, CARTA E CARTONE",
    "04": "RIFIUTI DELLA LAVORAZIONE DI PELLI E PELLICCE, NONCHÉ DELL'INDUSTRIA TESSILE",
    "05": "RIFIUTI DELLA RAFFINAZIONE DEL PETROLIO, PURIFICAZIONE DEL GAS NATURALE E TRATTAMENTO PIROLITICO DEL CARBONE",
    "06": "RIFIUTI DEI PROCESSI CHIMICI INORGANICI",
    "07": "RIFIUTI DEI PROCESSI CHIMICI ORGANICI",
    "08": "RIFIUTI DELLA PRODUZIONE, FORMULAZIONE, FORNITURA ED USO DI RIVESTIMENTI(PITTURE, VERNICI E SMALTI VETRATI), ADESIVI, SIGILLANTI E INCHIOSTRI PER STAMPA",
    "09": "RIFIUTI DELL'INDUSTRIA FOTOGRAFICA",
    "10": "RIFIUTI PRODOTTI DA PROCESSI TERMICI",
    "11": "RIFIUTI PRODOTTI DAL TRATTAMENTO CHIMICO SUPERFICIALE E DAL RIVESTIMENTO DI METALLI ED ALTRI MATERIALI; IDROMETALLURGIA NON FERROSA",
    "12": "RIFIUTI PRODOTTI DALLA LAVORAZIONE E DAL TRATTAMENTO FISICO E MECCANICO SUPERFICIALE DI METALLI E PLASTICA",
    "13": "OLI ESAURITI E RESIDUI DI COMBUSTIBILI LIQUIDI (tranne oli commestibili ed oli di cui ai capitoli 05, 12 e 19)",
    "14": "SOLVENTI ORGANICI, REFRIGERANTI E PROPELLENTI DI SCARTO (tranne 07 e 08)",
    "15": "RIFIUTI DI IMBALLAGGIO, ASSORBENTI, STRACCI, MATERIALI FILTRANTI E INDUMENTI PROTETTIVI (NON SPECIFICATI ALTRIMENTI)",
    "16": "RIFIUTI NON SPECIFICATI ALTRIMENTI NELL'ELENCO",
    "17": "RIFIUTI DELLE OPERAZIONI DI COSTRUZIONE E DEMOLIZIONE (COMPRESO IL TERRENO PROVENIENTE DA SITI CONTAMINATI)",
    "18": "RIFIUTI PRODOTTI DAL SETTORE SANITARIO E VETERINARIO O DA ATTIVITÀ DI RICERCA COLLEGATE(tranne i rifiuti di cucina e di ristorazione non direttamente provenienti da trattamento terapeutico)",
    "19": "RIFIUTI PRODOTTI DA IMPIANTI DI TRATTAMENTO DEI RIFIUTI, IMPIANTI DI TRATTAMENTO DELLE ACQUE REFLUE FUORI SITO, NONCHÉ DALLA POTABILIZZAZIONE DELL'ACQUA E DALLA SUA PREPARAZIONE PER USO INDUSTRIALE",
    "20": "RIFIUTI URBANI (RIFIUTI DOMESTICI E ASSIMILABILI PRODOTTI DA ATTIVITÀ COMMERCIALI E INDUSTRIALI NONCHÉ DALLE ISTITUZIONI) INCLUSI I RIFIUTI DELLA RACCOLTA DIFFERENZIATA"
  };

