const secondeDueCifre = {
"0101":"0101 Rifiuti prodotti dall'estrazione di minerali",
"0103":"0103 rifiuti prodotti da trattamenti chimici e fisici di minerali metalliferi",
"0104":"0104 rifiuti prodotti da trattamenti chimici e fisici di minerali non metalliferi",
"0105":"0105 fanghi di perforazione ed altri rifiuti di perforazione",
"0201":"0201 rifiuti prodotti da agricoltura, orticoltura, acquacoltura, selvicoltura, caccia e pesca",
"0202":"0202 rifiuti della preparazione e del trattamento di carne, pesce ed altri alimenti di origine animale",
"0203":"0203 rifiuti della preparazione e del trattamento di frutta, verdura, cereali, oli alimentari, cacao, caffè, tè e tabacco, della produzione di conserve alimentari, della produzione di lievito ed estratto di lievito , della preparazione e fermentazione di melassa",
"0204":"0204 rifiuti prodotti dalla raffinazione dello zucchero",
"0205":"0205 rifiuti dell'industria lattiero-casearia",
"0206":"0206 rifiuti dell'industria dolciaria e della panificazione",
"0207":"0207 rifiuti della produzione di bevande alcoliche ed analcoliche (tranne caffè, tè e cacao)",
"0301":"0301 rifiuti della lavorazione del legno e della produzione di pannelli e mobili",
"0302":"0302 rifiuti dei trattamenti conservativi del legno",
"0303":"0303 rifiuti della produzione e della lavorazione di polpa, carta e cartone",
"0401":"0401 rifiuti della lavorazione di pelli e pellicce",
"0402":"0402 rifiuti dell'industria tessile",
"0501":"0501 rifiuti della raffinazione del petrolio",
"0506":"0506 rifiuti prodotti dal trattamento pirolitico del carbone",
"0507":"0507 rifiuti prodotti dalla purificazione e dal trasporto di gas naturale",
"0601":"0601 rifiuti della produzione, formulazione, fornitura ed uso di acidi",
"0602":"0602 rifiuti della produzione, formulazione, fornitura ed uso di basi",
"0603":"0603 rifiuti della produzione, formulazione, fornitura ed uso di sali, loro soluzioni e ossidi metallici",
"0604":"0604 rifiuti contenenti metalli, diversi da quelli di cui alla voce 06 03",
"0605":"0605 fanghi prodotti dal trattamento in loco degli effluenti",
"0606":"0606 rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici contenenti zolfo, dei processi chimici dello zolfo e dei processi di desolforazione",
"0607":"0607 rifiuti della produzione, formulazione, fornitura ed uso di prodotti alogeni e dei processi chimici degli alogeni",
"0608":"0608 rifiuti della produzione, formulazione, fornitura ed uso del silicio e dei suoi derivati",
"0609":"0609 rifiuti della produzione, formulazione, fornitura ed uso di prodotti fosforosi e dei processi chimici del fosforo",
"0610":"0610 rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici contenenti azoto, dei processi chimici dell'azoto e della produzione di fertilizzanti",
"0611":"0611 rifiuti dalla produzione di pigmenti inorganici ed opacificanti",
"0613":"0613 rifiuti di processi chimici inorganici non specificati altrimenti",
"0701":"0701 rifiuti della produzione, formulazione, fornitura ed uso di prodotti chimici organici di base",
"0702":"0702 rifiuti della produzione, formulazione, fornitura ed uso (PFFU) di plastiche, gomme sintetiche e fibre artificiali",
"0703":"0703 rifiuti della produzione, formulazione, fornitura ed uso di coloranti e pigmenti organici (tranne 06 11)",
"0704":"0704 rifiuti della produzione, formulazione, fornitura ed uso di prodotti fitosanitari (tranne 02 01 08 e 02 01 09),agenti conservativi del legno (tranne 03 02) ed altri biocidi organici",
"0705":"0705 rifiuti della produzione, formulazione, fornitura ed uso di prodotti farmaceutici",
"0706":"0706 rifiuti della produzione, formulazione, fornitura ed uso di grassi, lubrificanti, saponi, detergenti, disinfettanti e cosmetici",
"0707":"0707 rifiuti della produzione, formulazione, fornitura ed uso di prodotti della chimica fine e di prodotti chimici non specificati altrimenti",
"0801":"0801 rifiuti della produzione, formulazione, fornitura ed uso e della rimozione di pitture e vernici",
"0802":"0802 rifiuti della produzione, formulazione, fornitura ed uso di altri rivestimenti (inclusi materiali ceramici)",
"0803":"0803 rifiuti della produzione, formulazione, fornitura ed uso di inchiostri per stampa",
"0804":"0804 rifiuti della produzione, formulazione, fornitura ed uso di adesivi e sigillanti (inclusi i prodotti impermeabilizzanti)",
"0805":"0805 rifiuti non specificati altrimenti alla voce 08",
"0901":"0901 rifiuti dell'industria fotografica",
"1001":"1001 rifiuti prodotti da centrali termiche ed altri impianti termici (tranne 19)",
"1002":"1002 rifiuti dell'industria del ferro e dell'acciaio",
"1003":"1003 rifiuti della metallurgia termica dell'alluminio",
"1004":"1004 rifiuti della metallurgia termica del piombo",
"1005":"1005 rifiuti della metallurgia termica dello zinco",
"1006":"1006 rifiuti della metallurgia termica del rame",
"1007":"1007 rifiuti della metallurgia termica di argento, oro e platino",
"1008":"1008 rifiuti della metallurgia termica di altri minerali non ferrosi",
"1009":"1009 rifiuti della fusione di materiali ferrosi",
"1010":"1010 rifiuti della fusione di materiali non ferrosi",
"1011":"1011 rifiuti della fabbricazione del vetro e di prodotti di vetro",
"1012":"1012 rifiuti della fabbricazione di prodotti di ceramica, mattoni, mattonelle e materiali da costruzione",
"1013":"1013 rifiuti della fabbricazione di cemento, calce e gesso e manufatti di tali materiali",
"1014":"1014 rifiuti prodotti dai forni crematori",
"1101":"1101 rifiuti prodotti dal trattamento e ricopertura di metalli(ad esempio, processi galvanici, zincatura, decapaggio, pulitura elettrolitica, fosfatazione, sgrassaggio con alcali, anodizzazione)",
"1102":"1102 rifiuti prodotti dalla lavorazione idrometallurgica di metalli non ferrosi",
"1103":"1103 rifiuti solidi e fanghi prodotti da processi di rinvenimento",
"1105":"1105 rifiuti prodotti da processi di galvanizzazione a caldo",
"1201":"1201 rifiuti prodotti dalla lavorazione e dal trattamento fisico e meccanico superficiale di metalli e plastiche",
"1203":"1203 rifiuti prodotti da processi di sgrassatura ad acqua e vapore (tranne 11)",
"1301":"1301 scarti di oli per circuiti idraulici",
"1302":"1302 scarti di olio motore, olio per ingranaggi e oli lubrificanti",
"1303":"1303 oli isolanti e termoconduttori di scarto",
"1304":"1304 oli di sentina",
"1305":"1305 prodotti di separazione olio/acqua",
"1307":"1307 rifiuti di carburanti liquidi",
"1308":"1308 rifiuti di oli non specificati altrimenti",
"1406":"1406 solventi organici, refrigeranti e propellenti di schiuma/aerosol di scarto",
"1501":"1501 imballaggi (compresi i rifiuti urbani di imballaggio oggetto di raccolta differenziata)",
"1502":"1502 assorbenti, materiali filtranti, stracci e indumenti protettivi",
"1601":"1601 veicoli fuori uso appartenenti a diversi modi di trasporto (comprese le macchine mobili non stradali) e rifiuti prodotti dallo smantellamento di veicoli fuori uso e dalla manutenzione di veicoli (tranne 13, 14, 16 06 e 16 08)",
"1602":"1602 scarti provenienti da apparecchiature elettriche ed elettroniche",
"1603":"1603 prodotti fuori specifica e prodotti inutilizzati",
"1604":"1604 esplosivi di scarto",
"1605":"1605 gas in contenitori a pressione e prodotti chimici di scarto",
"1606":"1606 batterie ed accumulatori",
"1607":"1607 rifiuti della pulizia di serbatoi per trasporto e stoccaggio e di fusti (tranne 05 e 13)",
"1608":"1608 catalizzatori esauriti",
"1609":"1609 sostanze ossidanti",
"1610":"1610 rifiuti liquidi acquosi destinati ad essere trattati fuori sito",
"1611":"1611 scarti di rivestimenti e materiali refrattari",
"1701":"1701 cemento, mattoni, mattonelle e ceramiche",
"1702":"1702 legno, vetro e plastica",
"1703":"1703 miscele bituminose, catrame di carbone e prodotti contenenti catrame",
"1704":"1704 metalli (incluse le loro leghe)",
"1705":"1705 terra (compreso il terreno proveniente da siti contaminati), rocce e fanghi di dragaggio",
"1706":"1706 materiali isolanti e materiali da costruzione contenenti amianto",
"1708":"1708 materiali da costruzione a base di gesso",
"1709":"1709 altri rifiuti dell'attività di costruzione e demolizione",
"1801":"1801 rifiuti dei reparti di maternità e rifiuti legati a diagnosi, trattamento e prevenzione delle malattie negli esseri umani",
"1802":"1802 rifiuti legati alle attività di ricerca e diagnosi, trattamento e prevenzione delle malattie negli animali",
"1901":"1901 rifiuti da incenerimento o pirolisi di rifiuti",
"1902":"1902 rifiuti prodotti da specifici trattamenti chimico-fisici di rifiuti industriali (comprese decromatazione, decianizzazione, neutralizzazione)",
"1903":"1903 rifiuti stabilizzati/solidificati (4)",
"1904":"1904 rifiuti vetrificati e rifiuti di vetrificazione",
"1905":"1905 rifiuti prodotti dal trattamento aerobico di rifiuti solidi",
"1906":"1906 rifiuti prodotti dal trattamento anaerobico dei rifiuti",
"1907":"1907 percolato di discarica",
"1908":"1908 rifiuti prodotti dagli impianti per il trattamento delle acque reflue, non specificati altrimenti",
"1909":"1909 rifiuti prodotti dalla potabilizzazione dell'acqua o dalla sua preparazione per uso industriale",
"1910":"1910 rifiuti prodotti da operazioni di frantumazione di rifiuti contenenti metallo",
"1911":"1911 rifiuti prodotti dalla rigenerazione dell'olio",
"1912":"1912 rifiuti prodotti dal trattamento meccanico dei rifiuti (ad esempio selezione, triturazione, compattazione, riduzione in pellet) non specificati altrimenti",

"1913":"1913 rifiuti prodotti dalle operazioni di bonifica di terreni e risanamento delle acque di falda",
"2001":"2001 frazioni oggetto di raccolta differenziata (tranne 15 01)",
"2002":"2002 rifiuti prodotti da giardini e parchi (inclusi i rifiuti provenienti da cimiteri)",
"2003":"2003 altri rifiuti urbani"}